baseURL = "https://baralga.tack.dev"
languageCode = "de-de"
title = "Baralga"
author = "Jan Stamer"
theme = "baralga"
[menu]
  [[menu.main]]
    name = "Blog"
    pre = "Blog"
    url = "/posts/"
    weight = 3
[markup.goldmark.renderer]
  unsafe= true
[params]
  twitter = "jsTamer21k"
  author = "Jan Stamer"
  description = "Jan Stamer - Coder und Creator von nachhaltigen Lösungen mit Java und Go. Teilt sein Wissen als Speaker und Autor."