[build]
  publish = "public"
  command = "hugo --gc --minify"

[context.production.environment]
  HUGO_VERSION = "0.92.1"
  HUGO_ENV = "production"
  HUGO_ENABLEGITINFO = "true"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Permissions-Policy = "fullscreen=*"
    Content-Security-Policy = "base-uri 'self'"
    Referrer-Policy = "same-origin"
    X-Content-Type-Options = "nosniff"